-- setup_features.sql
-- Run this in your Supabase SQL Editor to enable Ratings and Stats

-- 1. Add download_count to notes if not already present
ALTER TABLE public.notes 
ADD COLUMN IF NOT EXISTS download_count INT DEFAULT 0;

-- 2. Create Document Ratings Table
CREATE TABLE IF NOT EXISTS public.document_ratings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id BIGINT REFERENCES public.notes(id) ON DELETE CASCADE,
    user_id BIGINT REFERENCES public.users(id) ON DELETE CASCADE,
    rating INT CHECK (rating >= 1 AND rating <= 5),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    UNIQUE(document_id, user_id) -- Ensures a user can only rate a doc once
);

-- 3. Create User Reviews Table (Students rating other students)
CREATE TABLE IF NOT EXISTS public.user_reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reviewer_id BIGINT REFERENCES public.users(id) ON DELETE CASCADE,
    reviewee_id BIGINT REFERENCES public.users(id) ON DELETE CASCADE,
    rating INT CHECK (rating >= 1 AND rating <= 5),
    comment TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    UNIQUE(reviewer_id, reviewee_id) -- Ensures a student can only rate another student once
);

-- 4. Create an index for performance
CREATE INDEX IF NOT EXISTS idx_doc_ratings_doc ON public.document_ratings(document_id);
CREATE INDEX IF NOT EXISTS idx_user_reviews_reviewee ON public.user_reviews(reviewee_id);

-- 5. Create Password Resets Table
CREATE TABLE IF NOT EXISTS public.password_resets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email TEXT NOT NULL,
    token TEXT NOT NULL,
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);
