-- setup_admin.sql
-- Run this script in your Supabase SQL Editor to prepare the database for the Admin Panel.

-- 1. Add Role and Status to Users
ALTER TABLE public.users 
ADD COLUMN IF NOT EXISTS role varchar(50) DEFAULT 'user',
ADD COLUMN IF NOT EXISTS status varchar(50) DEFAULT 'active';

-- 2. Add Status to existing Notes table (which we will use for Documents)
-- By default, we mark existing notes as 'approved' so they don't disappear from the frontend
ALTER TABLE public.notes 
ADD COLUMN IF NOT EXISTS status varchar(50) DEFAULT 'approved';

-- 3. Create Requests Table
CREATE TABLE IF NOT EXISTS public.requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    description TEXT,
    user_id BIGINT REFERENCES public.users(id) ON DELETE CASCADE,
    status varchar(50) DEFAULT 'pending', -- pending, fulfilled
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 4. MAKE YOURSELF AN ADMIN
-- Please change 'your_email@example.com' to your actual login email to give yourself admin access.
-- UPDATE public.users SET role = 'admin' WHERE email = 'your_email@example.com';
